
***

# Calcul Matriciel
## TP6. Matching, Weddings and cie
***
***

In this practical, we are going to solve the perfect marriage  problem and implement Gale-Shapley algorithm, used to pair two populations based on each agent's preferences


***
***
A few ground rules for your report:
* _your code must be clear, commented and use explicit variable names_
* _every algorithm must be tested on a few examples which show the different use cases_
* _markdown comments and examples must be provided, and the report should be self-contained_

In [1]:
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
#magic
import warnings
warnings.filterwarnings('ignore')


***
## <font color=pink>Stable mariages</font>##
***

***

### _modelization of the problem_

the students and unis are represented by interger ranging from $0$ to $n-0$.

The preferences are given by two np array of shape $(n,n)$, <tt>prefStu</tt> and <tt>prefUni</tt> thus the preferences of student $i$ are given by <tt>prefStu[i]</tt>.

The marriages are going to be stored in the adjacency matrix $M$ of a (bipartite) graph whose vertices are students (numbered $0$ to $n-$) and unis (numbered $n+0$ to $n+n-0$).



**To Do:**

**_question 1_**

**a** Given arrays of $n$  students/universities, create a array of array for the preferences of each student/university (to have an example for next questions).



**b** using <tt>np.arange(n)</tt>, and <tt>np.random.permutation(a)</tt> ; create a random matrix of preferences of size $n \times n$.


**c** 
Write a function which determines weither a student (resp. a university) is married and to whom (use <tt>np.where</tt> for instance).


**d**
Write a function which determines if a university prefers a proposed marriage other its current one
Same thing for a student.


**d'** 
_(optional)_ Write a function which determines weither a marriage is stable or not.




One can compare and verify the solution using https://daffidwilde.github.io/matching/docs/tutorials/stable_marriage.html

In [2]:
#a


#b
def rand_pref(n):
    '''
    random preferences
    '''
    prefs=np.ndarray((n,n))
    for i in range(n):
        prefs[i]=np.random.permutation(n)
    return prefs 


print(rand_pref(6))



[[5. 2. 1. 4. 0. 3.]
 [0. 4. 1. 3. 5. 2.]
 [3. 2. 0. 1. 4. 5.]
 [0. 4. 3. 1. 2. 5.]
 [2. 3. 1. 0. 5. 4.]
 [3. 1. 4. 2. 0. 5.]]


In [4]:
#c


def IsMariedU(M,u):
    """
    #determines if and to whom uni u is matched in M 
    """      
    for i in range(len(M)//2):
        if M[u+len(M)//2][i]==1:
            return i

    return -1
# M is the adjency matrix of the bipartite graph where the first n nodes are the students and the last n nodes are the universities
M=np.array([[0,0,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,1],
            [0,0,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0],
            [0,1,0,0,0,0,0,0,0,0,0,0],
            [0,0,1,0,0,0,0,0,0,0,0,0],
            [0,0,0,1,0,0,0,0,0,0,0,0],
            [0,0,0,0,1,0,0,0,0,0,0,0],
            [0,0,1,0,0,0,0,0,0,0,0,0]])

print(IsMariedU(M,4))

def IsMariedS(M,s):
    """
    #determines if and to whom student s is matched in M 
    """    

    for i in range(len(M)//2,len(M)):
        if M[s][i]==1:
            return i-len(M)//2
    return -1

print(IsMariedS(M,2))

def IsCouple(M,s,u):
    """
    #determines if student s and uni u are matched in M
    """
    
    if IsMariedU(M,u)==s and IsMariedS(M,s)==u+len(M)//2:
        return True

    return False


print(IsCouple(M,2,5))

#d
def PrefersUni(M,prefUni,u,prop):
    """
    #determines if uni u prefers the proposition prop
    #to its current matching    
    """

    return -1

    
def PrefersStu(M,prefStu,s,prop):
    """
    determines if student s prefers the proposition prop
    to its current matching      
    """
  
    return -1

4
5
False


In [4]:
"""tests"""

1
1
True
False
[0 5 3 1 4 2]


**_question 2_**

Assemble the previous functions to get the Gale-Shapley algorithm.

In [10]:
###todo


def GaleShapley(studentPref,uniPref):
    """
        Stable marriage

        :param studentPref:  preferences of students
        :type studentPref: np array of dim 2
        :param uniPref:  preferences of universities
        :type uniPref: np array of dim 2
        :return: Stable marriage (adjacency matrix of bipartite graph)
        :rtype: np array of dim 2
    """      
    
    
    M=np.zeros((n+n,n+n),int)
    
    
           
    return M

**_bonus question 1_** 

Create a function ploting the marriages along the algorithm (idealy with dashed line and colours when a couple is broken)

**_bonus question 2_** 


Plot the average time of execution of the algorithm on (random) instances of size $n$.
Conjecture the average time complexity and compare to the (theoretical) worst case time complexity.

In [1]:
import time



**_bonus question 3_** 

Plot the average choice for student and uni on (random) instances of size $n$.

**_bonus question 4_** 

Implement and illustrate Irving stable roommates algorithm.